# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Dog-breeds-classifier',
                'doc_host': 'https://1nfiniteLo0p.github.io',
                'git_url': 'https://github.com/1nfiniteLo0p/Dog-breeds-classifier',
                'lib_path': 'Dog_breeds_classifier'},
  'syms': {'Dog_breeds_classifier.core': {'Dog_breeds_classifier.core.foo': ('core.html#foo', 'Dog_breeds_classifier/core.py')}}}
